---
version: "2.0"

services:
  akash:
    image: tombeynon/helium-on-akash:v0.0.2
    env:
      - AWS_ACCESS_KEY=yourkey
      - AWS_SECRET_KEY=yoursecret
      - S3_KEY_PATH=bucket/miner/swarm_key
    expose:
      - port: 2154
        as: 80
        to:
          - global: true

profiles:
  compute:
    akash:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 32Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        akash:
          denom: uakt
          amount: 10

deployment:
  akash:
    dcloud:
      profile: akash
      count: 1
